config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

 resources :articles
 resources :albums
 resources :scores
 resources :artists
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :score
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :artist
  belongs_to :album
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/score.rb
class Score < ApplicationRecord
	has_many:albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to @album
    else
      render :new
    end
  end

def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to root_path
  end

  private
    def album_params
      params.require(:album).permit(:title, :score_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

   private
    def article_params
      params.require(:article).permit(:artist_id, :album_id, :label, :year, :reviewer, :review_date)
    end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def index
    @artists = Artist.all
  end

def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artists
    else
      render :new
    end
  end

  private
    def artist_params
      params.require(:artist).permit(:name)
    end
end
  

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @scores= Score.all
  end

def new
    @score = Score.new
  end

  def create
    @score = Score.new(score_params)

    if @score.save
      redirect_to @scores
    else
      render :new
    end
  end

  private
    def score_params
      params.require(:score).permit(:number)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/albums/index.html.erb
<h1>Albums</h1>

<table>
  <tr>
    <th>Album</th>
    <th>Score</th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= link_to album.title, album %></td>
    <td><%=album.score.number %></td>
  </tr>
<% end %>
</table>
<br>
<button class="button button1"><%= link_to "New Album", new_album_path %></button>
<br>
<button class="button button1"><%= link_to "back", articles_path %></button>

app/views/albums/new.html.erb
<%= form_with model: @album do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_area :title %>
  </div>

  <div>
    <%= form.label :score_id %><br>
    <%= form.text_area :score_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/show.html.erb
<h1>Album and score</h1>

<p><%= @album.title %></p>

<p><%= @album.score.number %></p>
<ul>
<button class="button button1"><%= link_to "Destroy", album_path(@album),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></button>
</ul> 

<button class="button button1"><%= link_to "back", albums_path %></button>

app/views/articles/index.html.erb
<h1>BEST Albums</h1>

<button class="button button1"><%= link_to "Albums", albums_path %></button>
<button class="button button1"><%= link_to "Artists", artists_path %></button>
<button class="button button1"><%= link_to "Scores", scores_path %></button>


<table>
  <tr>
    <th>Artist</th>
    <th>Album</th>
    <th>Label</th>
    <th>Year</th>
    <th>Reviewer</th>
    <th>Review_date</th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= link_to article.artist.name, article %></td>
    <td><%= article.album.title %></td>
    <td><%= article.label %></td>
    <td><%= article.year %></td>
    <td><%= article.reviewer %></td>
    <td><%= article.review_date %></td>
  </tr>
<% end %>
</table>

<br>
<button class="button button1"><%= link_to "New Article", new_article_path %></button>

app/views/articles/new.html.erb
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :artist_id %><br>
    <%= form.text_field :artist_id %>
  </div>

  <div>
    <%= form.label :album_id %><br>
    <%= form.text_area :album_id %>
  </div>

  <div>
    <%= form.label :label %><br>
    <%= form.text_area :label %>
  </div>

  <div>
    <%= form.label :year %><br>
    <%= form.text_area :year %>
  </div>

  <div>
    <%= form.label :reviewer %><br>
    <%= form.text_area :reviewer %>
  </div>

  <div>
    <%= form.label :review_date %><br>
    <%= form.text_area :review_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.artist.name %></h1>

<p><%= @article.album.title %></p>
<p><%= @article.year %></p>
<p><%= @article.reviewer %></p>
<p><%= @article.review_date %></p>
<p><%= @article.album.score.number %></p>

<ul>
 <!-- <button class="button button1"><%= link_to "Edit", edit_article_path(@article) %></button> -->
 <button class="button button1"><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></button>
</ul> 
<button class="button button1"><%= link_to "back", articles_path %></button>

app/views/artists/index.html.erb
<h1>Artists</h1>

<table>
  <tr>
    <th>Artist</th>
  </tr>

<% @artists.each do |artist| %>
  <tr>
    <td><%=artist.name %></td>
  </tr>
<% end %>
</table>
<br>
<button class="button button1"><%= link_to "New Artist", new_artist_path %></button>
<br>
<button class="button button1"><%= link_to "back", articles_path %></button>
  

app/views/artists/new.html.erb
<%= form_with model: @artist do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_area :name %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/index.html.erb
<h1>Score</h1>

<table>
  <tr>
    <th>Score</th>
  </tr>

<% @scores.each do |score| %>
  <tr>
    <td><%=score.number %></td>
  </tr>
<% end %>
</table>

<br>
<button class="button button1"><%= link_to "New Score", new_score_path %></button>
<button class="button button1"><%= link_to "back", articles_path %></button>

  

app/views/scores/new.html.erb
<%= form_with model: @score do |form| %>
  <div>
    <%= form.label :number %><br>
    <%= form.text_area :number %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>